(*
 * THIS IS AN AUTO-GENERATED FILE PRODUCED BY URUZ!
 * DO NOT EDIT THIS FILE, since any changes will be
 * lost when the build is reset via "make clean".
 * This file is based on a user-specified EBNF
 * grammar, which can be edited as desired.
 *)

open Javascript_parser;;
open Javascript_lexer;;

let get_ast (i : in_channel) = 
   Javascript_parser.start Javascript_lexer.token (Lexing.from_channel i)
;;
